---
title: "Adaptamed - Dendro plots"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: yeti
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library('flexdashboard')
library('rgdal')
library("leaflet") 
library("leaflet.extras2")
library("sf")
library("tidyverse")
library("raster")
library("sp")
library("lubridate")
library("leafgl") # add large files points
library("simplevis")
library("leaflet.extras2")
```

```{r}
# Read life plots
c1 <- st_read("data/C1.shp", quiet = TRUE) 
c6 <- st_read("data/c6.shp", quiet = TRUE)
# aoi_sni <- st_transform(aoi_sni, crs = 4326)

parcelas <- st_read("data/geoinfo_dendro_adaptamed.shp", quiet = TRUE) 

parcelas_pinos <- 
  parcelas |> 
  filter(str_detect(Specie, "Pinus*")) |> 
  mutate(Specie = str_replace(Specie, "_", " "))
  
```


```{r}
popup_c1 <- paste0(
  "<strong>sitio:</strong> ", c1$site,
  "<br><strong>ID Cuadricula:</strong> ", c1$idCuadric,
  "<br><strong>Especie:</strong> ",  c1$spCode,
  "<br><strong>LAI:</strong> ", c1$lai
)

# code colors sp 
# pinaster, "#ffffbf", "beige"
# nigra, "#abdda4", "lightgreen"
# halepensis, "orange", "orange"
# sylvestris, "lightblue", "lightblue"

trees <- awesomeIconList(
  "Pinus pinaster" = makeAwesomeIcon(
    icon = "tree",
    markerColor = "white",
    library = "fa"
  ),
  "Pinus nigra" = makeAwesomeIcon(
    icon = "tree",
    markerColor = "lightgreen",
    library = "fa"
  ),
  "Pinus sylvestris" = makeAwesomeIcon(
    icon = "tree",
    markerColor = "lightblue",
    library = "fa"
  ),
  "Pinus halepensis" = makeAwesomeIcon(
    icon = "tree",
    markerColor = "orange",
    library = "fa"
  ))
  





#   ,
#   "Q. pyrenaica" = makeAwesomeIcon(
#     icon = "tree-deciduous",
#     markerColor = "goldenrod",
#     library = "fa"
#   ),
#   "Q. ilex" = makeAwesomeIcon(
#     icon = "tree-alt",
#     markerColor = "green",
#     library = "fa"
#   ),
#   "Q. pyrenaica // Q. ilex" = makeAwesomeIcon(
#     icon = "tree-alt",
#     markerColor = "red",
#     library = "fa"
#   ),
#   "Varias especies" = makeAwesomeIcon(
#     icon = "tree-alt",
#     markerColor = "white",
#     library = "fa"
#   )
# )



```

```{r}
leaflet(parcelas_pinos) |>
  addAwesomeMarkers(
    popup = ~paste0("<strong>Specie:</strong> ", parcelas_pinos$Specie, "</br>",
                    "<strong>Site:</strong> ", parcelas_pinos$site_code, "</br>",
                    "<strong>elev:</strong> ", parcelas_pinos$elev, "</br>",
                    "<strong>elev_category:</strong> ", parcelas_pinos$elev_code,"</br>", 
                    "<strong>LAI:</strong> ", parcelas_pinos$LAI,"</br>"),
    icon = ~ trees[Specie]
    ) |> 
  addProviderTiles("Esri.WorldImagery", group = "Satellite") |> 
  addWMSTiles("http://www.ign.es/wms-inspire/pnoa-ma",
    layers = "OI.OrthoimageCoverage",
    group = "PNOA Máxima Actualidad",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = FALSE),
    attribution = 'PNOA cedido por © <a href="http://www.ign.es/ign/main/index.do" target="_blank">Instituto Geográfico Nacional de España</a>'
  ) |> 
   addWMSTiles(
    baseUrl = "https://www.ideandalucia.es/wms/mta100v_2005?",
    layers = "Curvas_Altimetricas",
    group = "Curvas Nivel",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = TRUE),
    attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>'
  ) |> 
  addWMSTiles(
    baseUrl = "http://www.ideandalucia.es/wms/mdt_2005?",
    layers = "Sombreado_10",
    group = "Hillshade",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = TRUE),
    attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>'
  ) |>
  addWMSTiles(
    baseUrl = "http://www.ign.es/wms-inspire/ign-base?",
    layers = "IGNBaseTodo",
    group = "Basemap",
    attribution = '© <a href="http://www.ign.es/ign/main/index.do" target="_blank">Instituto Geográfico Nacional de España</a>'
  ) |>  
  addWMSTiles("http://www.ideandalucia.es/services/toporaster10/wms?",
    layers = "toporaster10",
    group = "Topographical",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = FALSE),
    attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>'
  ) |>
  addWMSTiles("http://www.ideandalucia.es/wms/mta10r_2001-2013?",
    layers = "mta10r_2001-2013",
    group = "topo2013",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = FALSE),
    attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>'
  ) |> 
  addWMSTiles("http://www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_Ortofoto_Andalucia_1956?",
    layers = "ortofoto_1956",
    group = "orto1956",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = FALSE),
    attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>'
  ) |> 
  addWMSTiles("http://www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_Ortofoto_BN_1977_83?",
    layers = "orto_BN_77_83",
    group = "orto77-78",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = FALSE),
    attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>'
  ) |> 
  addWMSTiles("https://www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_Ortofoto_PAN_Andalucia_84_85",
    layers = "orto_1984_85",
    group = "orto84-85",
    options = WMSTileOptions(
      format = "image/png", 
      transparent = FALSE),
    attribution = '<a href="http://www.juntadeandalucia.es/institutodeestadisticaycartografia" target="_blank">Instituto de Estadística y Cartografía de Andalucía</a>'
  ) |> 
  addPolygons(
    data = c1,
    group = "C1-Adpatamed",
    fillColor = "green", fillOpacity = 0.6,
    stroke = TRUE, color= "blue", weight = 1,
    popup = popup_c1,
    label = ~CUADRICULA,
    labelOptions = labelOptions(
      noHide = FALSE,
      offset = c(0, 0),
      textOnly = F,
      style = list("color" = "black")
    )
  )  |> 
  addLayersControl(
    position = "bottomright",
    baseGroups = c("Basemap", "PNOA Máxima Actualidad", "Satellite", "Hillshade", "Topographical", "topo2013", "orto1956", "orto77-78", "orto84-85"),
    overlayGroups = c("C1-Adpatamed", "Curvas Nivel"), 
    options = layersControlOptions(collapsed = TRUE)
  ) |> 
  hideGroup("Curvas Nivel")


```


```{r, eval=FALSE}
# |> 
#   addWMSTiles("http://www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_distribucion_pinus_pinaster?", 
#               layers = "distrib_pinus_pinaster", 
#               group = "P. pinaster", 
#               options = WMSTileOptions(
#       format = "image/png", 
#       transparent = TRUE)) |> 
#   addWMSTiles("https://www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_distribucion_pinus_nigra?", 
#               layers = "distrib_pinus_nigra", 
#               group = "P. nigra", 
#               options = WMSTileOptions(
#       format = "image/png", 
#       transparent = TRUE)) |>
#   addWMSTiles("https://www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_distribucion_pinus_halepensis?", 
#               layers = "pino_carrasco", 
#               group = "P. halepensis", 
#               options = WMSTileOptions(
#       format = "image/png", 
#       transparent = TRUE)) |> 
#   addProviderTiles("Esri.WorldImagery", group = "Satellite") |> 
#   addWMSTiles("http://www.ign.es/wms-inspire/pnoa-ma",
#     layers = "OI.OrthoimageCoverage",
#     group = "PNOA Máxima Actualidad",
#     options = WMSTileOptions(
#       format = "image/png", 
#       transparent = FALSE),
#     attribution = 'PNOA cedido por © <a href="http://www.ign.es/ign/main/index.do" target="_blank">Instituto Geográfico Nacional de España</a>'
#    ) |> 
```

